name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build Plugin"
    runs-on: ubuntu-latest
    steps:
      - name: "Repository checkout"
        uses: "actions/checkout@v4"
  
      - name: "NPM Build"
        run: |
          npm install
          npm run buildgithub
