name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "25 23 * * *"
  workflow_dispatch:

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: plugin